services:
  postgres_db:
    image: postgres:17.9
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - project_network

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure_service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: "TRUE"
      MAKE_REPORT_ON_START: "TRUE"
    ports:
      - "5050:5050"
    volumes:
      - ./target/allure-results:/app/allure-results
    networks:
      - project_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
  jenkins_data: